# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afe26ee4926cc2fd19389b102f4e007aebc2a9d41e73d84c6723b763822e852f4b7490dcb3baf26410b7a1e72cc54d12168a409dc6a5b87e12817cf55aaac3bb

test:
  secret_key_base: 7b17b3cb3cf802c8e08588f544355f0829cc8d06b4b2c7a00d803c9755a703d010c59c598f3203221feae11b5c73dcbe19867d2a8526852f292123aa149ece6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
